apiVersion: apps/v1
kind: Deployment 
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2 
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: 48483/weatherwisefrontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000 


---

apiVersion: v1 
kind: Service 
metadata: 
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: "TCP"
      port: 3000 
      targetPort: 3000 
  type: LoadBalancer
