apiVersion: v1
kind: Service
metadata:
  name: frontend-ssvc
  namespace: webapps
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: webapps
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: 48483/weatherwisefrontend:latest
          name: frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
